"""excursions sign ups table

Revision ID: a447e717aac4
Revises: 4ba9f3750cef
Create Date: 2025-08-18 13:32:19.764750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a447e717aac4'
down_revision: Union[str, Sequence[str], None] = '4ba9f3750cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excursions_signups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excursions_signups')
    # ### end Alembic commands ###
