"""first

Revision ID: 6d6c80cb3f19
Revises: 
Create Date: 2025-09-22 02:57:39.934011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6c80cb3f19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('event', 'excursion', name='eventtypeenum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('excursions_signups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=200), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('telegram', 'local', 'url', name='sourcetypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pin',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('patronym', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('pin')
    op.drop_table('media')
    op.drop_table('excursions_signups')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
